### ISSUE TITLE
eventid 4624 description

### ISSUE THREAD

**Issue by nembo81** [mdecrevoisier/Microsoft-eventlog-mindmap#1]
Hi there!
The 4624 eventid is wrong - the right description is "An Account Was Successfully Logged On"
If you want to add the eventid 4634, that's the one related to "An account was logged off"

**Comment by mdecrevoisier** [comment]
Hi Nembo81, I appreciated you look at the mindmap and spotted the mistake. I have just released a new version with the fix. Many thanks

**Comment by nembo81** [comment]
No problem at all - thanks for this awesome mindmap!
