### ISSUE TITLE
Great project. Would you consider an additional Event ID 

### ISSUE THREAD

**Issue by jagjag6** [mdecrevoisier/Microsoft-eventlog-mindmap#2]
Hi Michel
Great work. The mindmaps are brilliant, thank you for a great resource.

I don't know if you consider adding additional event id's, here is my suggestion

Some environments monitor printing and would benefit from having print name jobs in the event logs.
Microsoft-Windows-PrintService/Operational
Event ID: 307

Requires GPO 
Computer Configuration -> Policies -> Administrative Templates -> Printers
Allow job name in event logs: Enabled

And KB2919355 must be installed
REF: https://social.technet.microsoft.com/Forums/windowsserver/en-US/cc1d8cf1-9f19-47f4-bc6f-5e771d5909e6/windows-2012-r2-kb2919355-installed-quotallow-job-name-in-event-logsquot-enabled-in-gpo-but?forum=winserverprint

**Comment by mdecrevoisier** [comment]
Hi @jagjag6,
Feedbacks are always welcome ! I have merged your improvement together with some others ones that I have pending. Map is now updated. Thanks you for your contribution !
